
sequenceDiagram
   title Media Upload Sequence Diagram

    participant Client
    participant Gateway
    participant Media
    participant MinIO

    Client->>Gateway: Upload Request

    Gateway->>Media: Generate Signed URL

    Media-->>Gateway: Signed URL

    Gateway-->>Client: Signed URL

    Client->>MinIO: Direct Upload