---
title: "Observability Diagram"
---

flowchart TB

    SERVICES["All Services"]

    OTEL["OpenTelemetry"]

    PROM["Prometheus"]
    LOKI["Loki"]
    TEMPO["Tempo"]

    GRAFANA["Grafana"]

    SERVICES --> OTEL

    OTEL --> PROM
    OTEL --> LOKI
    OTEL --> TEMPO

    PROM --> GRAFANA
    LOKI --> GRAFANA
    TEMPO --> GRAFANA