// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is satisfied by *pgxpool.Pool, *pgx.Conn, and *pgx.Tx.
// Using this interface lets Queries work inside and outside transactions
// without any code changes in the caller.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// Queries is the generated query runner.
type Queries struct {
	db DBTX
}

// New returns a Queries bound to db.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a Queries scoped to an active transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
