// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth_schema.refresh_tokens (
    id,
    user_id,
    token_hash,
    family,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    user_id,
    token_hash,
    family,
    used,
    expires_at,
    created_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	Family    uuid.UUID `db:"family" json:"family"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

// Called by: AuthService.issuePairTx (login and refresh paths)
// used defaults to FALSE via the table DEFAULT — not passed explicitly.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthSchemaRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Family,
		arg.ExpiresAt,
	)
	var i AuthSchemaRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM auth_schema.refresh_tokens
WHERE expires_at < NOW()
`

// Called by: background cleanup goroutine in main.go (every hour).
// The partial index on (expires_at) WHERE used = FALSE keeps this fast.
func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
DELETE FROM auth_schema.refresh_tokens
WHERE user_id = $1
`

// Called by: account deletion handler (Phase 2).
// The FK CASCADE already handles this when DeleteUser fires, but this
// query is useful when revoking all sessions without deleting the account.
func (q *Queries) DeleteUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, userID)
	return err
}

const getActiveTokensByUser = `-- name: GetActiveTokensByUser :many
SELECT
    id,
    user_id,
    token_hash,
    family,
    used,
    expires_at,
    created_at
FROM auth_schema.refresh_tokens
WHERE user_id    = $1
  AND used       = FALSE
  AND expires_at > NOW()
ORDER BY created_at DESC
`

// Called by: session listing handler (Phase 2).
// Returns non-expired, unused tokens ordered newest first.
func (q *Queries) GetActiveTokensByUser(ctx context.Context, userID uuid.UUID) ([]AuthSchemaRefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSchemaRefreshToken{}
	for rows.Next() {
		var i AuthSchemaRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Family,
			&i.Used,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
    id,
    user_id,
    token_hash,
    family,
    used,
    expires_at,
    created_at
FROM auth_schema.refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

// Called by: AuthService.Refresh, AuthService.Logout
// The token_hash column has a UNIQUE index — this is always an index scan.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AuthSchemaRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i AuthSchemaRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT
    id,
    user_id,
    token_hash,
    family,
    used,
    expires_at,
    created_at
FROM auth_schema.refresh_tokens
WHERE id = $1
LIMIT 1
`

// Reserved for internal admin/audit use.
func (q *Queries) GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (AuthSchemaRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i AuthSchemaRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateTokenFamily = `-- name: InvalidateTokenFamily :exec
DELETE FROM auth_schema.refresh_tokens
WHERE family = $1
`

// Called by: AuthService.Refresh (reuse detected), AuthService.Logout
// Deletes ALL tokens in the family — burns every session in the login chain.
func (q *Queries) InvalidateTokenFamily(ctx context.Context, family uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateTokenFamily, family)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :one
UPDATE auth_schema.refresh_tokens
SET used = TRUE
WHERE id = $1
RETURNING
    id,
    user_id,
    token_hash,
    family,
    used,
    expires_at,
    created_at
`

// Called by: AuthService.Refresh inside ExecTx
// Marks the consumed token so any replay is detected on the next attempt.
// Returns the full row so callers can assert the state transition.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) (AuthSchemaRefreshToken, error) {
	row := q.db.QueryRow(ctx, markRefreshTokenUsed, id)
	var i AuthSchemaRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
