// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth_schema.users (
    id,
    email,
    password_hash,
    is_verified
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    email,
    password_hash,
    is_verified,
    created_at,
    updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	IsVerified   bool      `db:"is_verified" json:"is_verified"`
}

// Called by: AuthService.Register
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthSchemaUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.IsVerified,
	)
	var i AuthSchemaUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM auth_schema.users
WHERE id = $1
`

// Called by: account deletion handler (Phase 2)
// Cascade in the FK deletes all refresh_tokens rows automatically.
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    password_hash,
    is_verified,
    created_at,
    updated_at
FROM auth_schema.users
WHERE email = $1
LIMIT 1
`

// Called by: AuthService.Login, AuthService.Register (existence check)
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthSchemaUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthSchemaUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    password_hash,
    is_verified,
    created_at,
    updated_at
FROM auth_schema.users
WHERE id = $1
LIMIT 1
`

// Called by: AuthService.Refresh (resolve user after token lookup)
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthSchemaUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthSchemaUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE auth_schema.users
SET
    is_verified = TRUE,
    updated_at  = NOW()
WHERE id = $1
RETURNING
    id,
    email,
    password_hash,
    is_verified,
    created_at,
    updated_at
`

// Called by: email verification handler (Phase 2)
func (q *Queries) MarkUserVerified(ctx context.Context, id uuid.UUID) (AuthSchemaUser, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var i AuthSchemaUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE auth_schema.users
SET
    password_hash = $1,
    updated_at    = NOW()
WHERE id = $2
RETURNING
    id,
    email,
    password_hash,
    is_verified,
    created_at,
    updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	ID           uuid.UUID `db:"id" json:"id"`
}

// Called by: AuthService.Login transparent rehash (NeedsRehash path)
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (AuthSchemaUser, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i AuthSchemaUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
